services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Веб-консоль
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password12345     # минимум 8 символов
    volumes:
      - "D:/3rd years/Data engineering/minio/data:/data"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3